# =============================================================================
# GUITAR STUDIO IA - Copyright (c) 2026 MATHEUS ABELARDO TREVENZOLI ARAUJO
# Configurações de Dimensões e Offsets dos Componentes de UI
# =============================================================================

# --- CONFIGURAÇÕES GERAIS DE LAYOUT (DASHBOARD) ---
# Estas larguras servem como base para o alinhamento centralizado
LARGURA_TOOLBAR_PADRAO = 700
LARGURA_INFERIOR_PADRAO = 1200

# --- TOP BAR (dragger_controles_topo) ---
TOPBAR_MIN_LARGURA = 650
TOPBAR_PIN_OFFSET_X = 70
TOPBAR_PIN_Y = 25
TOPBAR_PIN_TAMANHO = 45
TOPBAR_Y_INICIAL = 40
TOPBAR_ALTURA = 40

# --- GUITAR NECK (dragger_guitarra) ---
GUITAR_Y_INICIAL = 120
GUITAR_ALTURA_BRACO = 280
GUITAR_RAIO_NOTA = 16
GUITAR_RAIO_DETECTADA = 20
GUITAR_ALPHA_NORMAL = 255
GUITAR_ALPHA_INATIVO = 90

# --- CHORD SELECTOR (dragger_acordes) ---
CHORD_ALTURA = 120
CHORD_OFFSET_Y_BRACO = 100
CHORD_OFFSET_Y_INTERNO = 10

# --- AUDIO SIDEBAR (dragger_nota_atual) ---
SIDEBAR_NOTA_LARGURA = 280
SIDEBAR_NOTA_ALTURA = 220
SIDEBAR_NOTA_OFFSET_X = 30
SIDEBAR_NOTA_OFFSET_Y = 15
SIDEBAR_NOTA_OFFSET_Y_BOTTOM = 470 # Distância do fundo da tela
SIDEBAR_NOTA_OFFSET_INTERNO_X = 25
SIDEBAR_NOTA_OFFSET_INTERNO_Y = 15
SIDEBAR_LABEL_OFFSET_Y = 55
SIDEBAR_GRID_NOTAS_Y = 85
SIDEBAR_SLIDER_OFFSET_Y = 50
SIDEBAR_SLIDER_ALTURA_PROX = 42

# --- METRÔNOMO (dragger_metronomo) ---
METRO_LARGURA = 240
METRO_ALTURA = 100
METRO_OFFSET_X = 30 # Offset em relação ao ChordSelector
METRO_OFFSET_Y_ESTUDO = 30 # Quando jogado para baixo

# --- PAINEL DE CORES (dragger_cores) ---
CORES_LARGURA = 180
CORES_ALTURA = 150
CORES_OFFSET_X = 30
CORES_OFFSET_Y_BOTTOM = 220 # Distância do fundo da tela

# --- BOTTOM NAV (dragger_painel_inferior) ---
BOTTOM_ALTURA_CAIXA = 300
BOTTOM_OFFSET_AREA_DESENHO = 55
BOTTOM_OFFSET_CLIPPING_Y = -10
BOTTOM_ALTURA_UTIL_DIFF = 70
BOTTOM_MARGIN_X = 20
BOTTOM_SUBABA_Y_OFFSET = 12
BOTTOM_SUBABA_ALTURA = 32
BOTTOM_SUBABA_MARGIN_X = 40
BOTTOM_Y_OFFSET_TELA = 65 # Offset em relação ao fundo da tela
BOTTOM_Y_AREA_DESENHO_OFFSET = 290 # Offset para Y_AREA_DESENHO

# --- FABRICA DE ESCALAS (CARDS) ---
CARDS_GAP_HORIZONTAL = 40
CARDS_GAP_VERTICAL = 250
CARDS_ESC_LARGURA = 0.5
CARDS_ESC_INTERNA = 0.60
CARDS_TEXTO_OFFSET_Y = -15
CARDS_OFFSET_X_INICIAL = 25
FABRICA_Y_BASE_OFFSET = 80
FABRICA_LARG_UTIL_MARGIN = 50

# --- CONFIGURAÇÕES E ESTUDOS ---
CONFIG_OFFSET_Y_INTERNO = 10
ESTUDOS_OFFSET_Y_INTERNO = 10
ESTUDOS_DESC_OFFSET_X = 210
